/**
 * Generate editorial letter from analysis results
 */

import { ProjectSettings } from '@/types';

export interface EditorialLetterData {
  projectTitle: string;
  settings: ProjectSettings;
  manuscript: {
    wordCount: number;
    chapterCount: number;
    sceneCount: number;
  };
  issues: {
    critical: number;
    major: number;
    minor: number;
    suggestion: number;
  };
  topIssues: Array<{
    category: string;
    title: string;
    description: string;
    suggestion: string;
  }>;
  strengths?: string[];
  storyBible?: any;
}

export function generateEditorialLetter(data: EditorialLetterData): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `# Editorial Letter: ${data.projectTitle}

**Date:** ${date}  
**Manuscript Length:** ${data.manuscript.wordCount.toLocaleString()} words  
**Structure:** ${data.manuscript.chapterCount} chapters, ${data.manuscript.sceneCount} scenes  
**Subgenre:** ${data.settings.subgenre}  
**Heat Level:** ${data.settings.heatLevel}  
**Tropes:** ${data.settings.tropes.join(', ')}  

---

## Overview

Thank you for entrusting me with your manuscript, "${data.projectTitle}." I've completed my editorial review, examining the story from developmental structure through line-level craft. This letter outlines my key observations and recommendations to help you strengthen this ${data.settings.subgenre} romance.

${data.strengths && data.strengths.length > 0 ? `
## Strengths

Before diving into revisions, I want to highlight what's working well:

${data.strengths.map(s => `- ${s}`).join('\n')}

These elements form a strong foundation for your story. As you revise, keep these strengths at the forefront.
` : ''}

## Analysis Summary

My review identified **${data.issues.critical + data.issues.major + data.issues.minor + data.issues.suggestion} areas** for consideration:

- **Critical Issues:** ${data.issues.critical} (require immediate attention)
- **Major Issues:** ${data.issues.major} (significant impact on reader experience)
- **Minor Issues:** ${data.issues.minor} (polish and refinement)
- **Suggestions:** ${data.issues.suggestion} (optional enhancements)

## Priority Recommendations

Based on my analysis, here are the most important areas to address in your revision:

${data.topIssues.slice(0, 7).map((issue, index) => `
### ${index + 1}. ${issue.title} (${issue.category})

**Issue:** ${issue.description}

**Recommendation:** ${issue.suggestion}
`).join('\n')}

## Romance Arc Considerations

For ${data.settings.subgenre} romance, readers expect certain emotional beats and relationship milestones. Ensure your story delivers:

${getGenreGuidance(data.settings.subgenre)}

## Revision Plan

I recommend addressing issues in this order:

1. **First Pass - Structure (Weeks 1-2)**
   - Address critical developmental issues
   - Ensure romance arc progression is clear
   - Strengthen emotional beats and turning points

2. **Second Pass - Character & Scene (Weeks 3-4)**
   - Deepen character motivations
   - Enhance chemistry and emotional connection
   - Polish individual scenes for clarity and impact

3. **Third Pass - Line Level (Week 5)**
   - Address repetition and filter words
   - Vary sentence structure
   - Polish dialogue and eliminate clichés

4. **Final Polish (Week 6)**
   - Read aloud for flow
   - Final grammar and punctuation check
   - Consistency pass

## Next Steps

Once you've completed your revision:

1. Let the manuscript rest for at least a week
2. Read through with fresh eyes
3. Consider beta readers for feedback
4. Final proofread before submission

${data.issues.critical > 5 ? `
**Note:** Given the number of critical issues identified, I recommend focusing on the big-picture structural concerns before diving into line edits. The story's foundation needs to be solid before polishing individual sentences.
` : ''}

## Closing Thoughts

You have ${data.manuscript.wordCount < 60000 ? 'a lean, focused' : data.manuscript.wordCount > 100000 ? 'an expansive, detailed' : 'a well-paced'} manuscript with clear ${data.settings.subgenre} romance elements. The ${data.settings.tropes.join(' and ')} ${data.settings.tropes.length > 1 ? 'tropes' : 'trope'} ${data.settings.tropes.length > 1 ? 'are' : 'is'} evident and will resonate with readers who love this combination.

Focus on the priority recommendations above, and remember that revision is where good stories become great. Trust your instincts, stay true to your voice, and don't be afraid to make bold choices that serve your story.

I'm excited to see where you take this manuscript. If you have questions about any of the feedback, please don't hesitate to reach out.

Best wishes with your revisions!

---

*This editorial letter was generated by Romance Editor AI and should be used in conjunction with the detailed issue list and suggested revisions.*
`;
}

function getGenreGuidance(subgenre: string): string {
  const guidance: { [key: string]: string } = {
    'contemporary': `- Modern, relatable conflicts and settings
- Strong character development and internal growth
- Authentic dialogue and emotional honesty
- Satisfying HEA (Happily Ever After) or HFN (Happy For Now)`,
    
    'historical': `- Period-appropriate language and setting details
- Historical accuracy balanced with romantic fantasy
- Social constraints that create meaningful conflict
- Attention to power dynamics and consent within historical context`,
    
    'romantic-suspense': `- Escalating external danger that impacts the relationship
- Trust issues that must be overcome
- Action sequences balanced with emotional intimacy
- Resolution that addresses both the romance and the suspense plot`,
    
    'paranormal': `- Clear worldbuilding rules for supernatural elements
- How the paranormal affects the relationship dynamic
- Stakes that feel personal despite fantastical elements
- Satisfying integration of magic/supernatural with romance`,
    
    'fantasy-romance': `- Rich worldbuilding that serves the romance
- Magic system that creates both obstacles and opportunities
- Epic stakes balanced with intimate character moments
- Clear relationship development despite external conflicts`,
    
    'ya-romance': `- Age-appropriate emotional maturity
- First-love intensity and discovery
- Coming-of-age themes integrated with romance
- Authentic teen voice and concerns`,
    
    'romcom': `- Sharp, witty dialogue
- Comedic situations that reveal character
- Laugh-out-loud moments balanced with genuine emotion
- Light tone that doesn't sacrifice emotional authenticity`,
  };

  return guidance[subgenre] || `- Clear romance arc with emotional development
- Satisfying resolution of conflicts
- Strong chemistry between protagonists
- Genre expectations met while maintaining originality`;
}
